#!/usr/bin/with-contenv bash

cd /c9sdk
HOME=/c9bins exec \
	s6-setuidgid hostingjaya \
	/c9bins/.c9/node/bin/node server.js --listen 0.0.0.0 --packed -p 8000 -w /workspace -a "${USERNAME}:${PASSWORD}"
