ARG COMPOSE_VERSION="1.29.2"

# docker compose
FROM ghcr.io/linuxserver/docker-compose:amd64-version-${COMPOSE_VERSION} AS compose

# runtime stage
FROM gvoze32/cloud9-base:amd64-jammy

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="c9cli version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="gvoze32"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN \
 echo "**** install docker deps ****" && \
 install -m 0755 -d /etc/apt/keyrings && \
 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
 chmod a+r /etc/apt/keyrings/docker.gpg && \
 echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable' > \
    /etc/apt/sources.list.d/docker-ce.list && \
 apt-get update && \
 apt-get install -y --no-install-recommends \
    docker-ce \
    docker-compose-plugin && \
 echo "**** Cleanup and user perms ****" && \
 apt-get autoclean && \
 rm -rf \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /tmp/*
