FROM ghcr.io/linuxserver/baseimage-cloud9:files as builder
FROM ghcr.io/linuxserver/baseimage-ubuntu:jammy

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="c9cli version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="gvoze32"

# add files from c9base
COPY --from=builder /buildout/ /

RUN \
 useradd -m -s /bin/bash hostingjaya && \
 echo "**** install base packages ****" && \
 apt-get update && \
 apt-get install -y --no-install-recommends \
    curl \
    git \
    gnupg \
    sudo \
    unzip \
    zip && \
 echo "**** Cleanup and user perms ****" && \
 usermod -aG sudo \
    hostingjaya && \
 apt-get autoclean && \
 rm -rf \
        /var/lib/apt/lists/* \
        /var/tmp/* \
        /tmp/*
        
# add local files
COPY root/ /

# ports and volumes
EXPOSE 8000
VOLUME /workspace