ARG COMPOSE_VERSION="1.29.2"

# docker compose
FROM ghcr.io/linuxserver/docker-compose:amd64-version-${COMPOSE_VERSION} as compose

# runtime stage
FROM gvoze32/cloud9-base:alpine

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="c9cli version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="gvoze32"

# Docker compose
COPY --from=compose /usr/local/bin/docker-compose /usr/local/bin/docker-compose

RUN \
echo "**** Installing dependencies ****" && \
apk add --no-cache \
    curl \
    bash \
    docker && \
echo "**** Cleanup ****" && \
rm -rf /var/cache/apk/*