FROM ghcr.io/linuxserver/baseimage-cloud9:files as builder
FROM ghcr.io/linuxserver/baseimage-fedora:40

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="c9cli version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="gvoze32"

# add files from c9base
COPY --from=builder /buildout/ /

RUN \
 echo "**** install base packages ****" && \
 dnf -y update && \
 dnf -y install \
    curl \
    git \
    gnupg2 \
    sudo \
    unzip \
    zip && \
 echo "**** Cleanup and user perms ****" && \
 usermod -aG wheel \
    abc && \
 dnf clean all && \
 rm -rf \
        /var/cache/dnf \
        /var/tmp/* \
        /tmp/*

# add local files
COPY root/ /

# ports and volumes
EXPOSE 8000
VOLUME /code
