FROM ghcr.io/linuxserver/baseimage-cloud9:files as builder
FROM ghcr.io/linuxserver/baseimage-alpine:3.20

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="c9cli version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="gvoze32"

# add files from c9base
COPY --from=builder /buildout/ /

RUN \
  echo "**** install base packages ****" && \
  apk add --no-cache \
    curl \
    git \
    gnupg \
    sudo \
    unzip \
    zip && \
  echo "**** Add user permissions ****" && \
  { \
    addgroup -S abc || true; \
    adduser -S abc -G abc || true; \
  } && \
  echo "abc ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
  echo "**** Cleanup ****" && \
  rm -rf /var/cache/apk/* /tmp/*

# add local files
COPY root/ /

# ports and volumes
EXPOSE 8000
VOLUME /code
