ARG COMPOSE_VERSION="1.29.2"

# docker compose
FROM ghcr.io/linuxserver/docker-compose:amd64-version-${COMPOSE_VERSION} as compose

# runtime stage
FROM gvoze32/cloud9-base:noble

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="c9cli version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="gvoze32"

# Docker compose
COPY --from=compose /usr/local/bin/docker-compose /usr/local/bin/docker-compose

RUN \
 echo "**** install docker deps ****" && \
 dnf -y install dnf-plugins-core && \
 dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo && \
 dnf -y install docker-ce docker-ce-cli containerd.io && \
 echo "**** Cleanup and user perms ****" && \
 dnf clean all && \
 rm -rf \
    /var/cache/dnf \
    /var/tmp/* \
    /tmp/*
