FROM ghcr.io/linuxserver/baseimage-cloud9:files as builder
FROM ghcr.io/linuxserver/baseimage-alpine:3.20

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="c9cli version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="gvoze32"

# add files from c9base
COPY --from=builder /buildout/ /

RUN \
  echo "**** install base packages ****" && \
  apk -U --no-cache --no-progress upgrade && \
  apk -U --no-cache --force --no-progress add \
      bash \
      tmux \
      sudo \
      git \
      gnupg \
      make \
      gcc \
      g++ \
      python \
      sqlite \
      wget \
      curl \
      openssl \
      ca-certificates \
      zip \
      unzip \
      nodejs \
      npm &&\
  mkdir -p ./node/bin ./bin ./node_modules &&\
  ln -sf "`which tmux`" ./bin/tmux &&\
  ln -s "`which node`" ./node/bin/node &&\
  ln -s "`which npm`" ./node/bin/npm &&\
  echo "**** Add user permissions ****" && \
  { \
    addgroup -S abc || true; \
    adduser -S abc -G abc || true; \
  } && \
  echo "abc ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
  echo "**** Cleanup ****" && \
  rm -rf /var/cache/apk/* /tmp/*

# add local files
COPY root/ /

# ports and volumes
EXPOSE 8000
VOLUME /code
