name: Base Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: focal
            arch: amd64
            platform: linux/amd64
            dockerfile: dockerfiles/base/Dockerfile-focal
            tags: |
              gvoze32/cloud9-base:focal
              gvoze32/cloud9-base:amd64-focal
          - distro: jammy
            arch: amd64
            platform: linux/amd64
            dockerfile: dockerfiles/base/Dockerfile-jammy
            tags: |
              gvoze32/cloud9-base:jammy
              gvoze32/cloud9-base:amd64-jammy
          - distro: noble
            arch: amd64
            platform: linux/amd64
            dockerfile: dockerfiles/base/Dockerfile-noble
            tags: |
              gvoze32/cloud9-base:noble
              gvoze32/cloud9-base:amd64-noble
              gvoze32/cloud9-base:latest
          - distro: focal
            arch: arm64v8
            platform: linux/arm64/v8
            dockerfile: dockerfiles/base/Dockerfile-focal
            tags: |
              gvoze32/cloud9-base:arm64v8-focal
          - distro: jammy
            arch: arm64v8
            platform: linux/arm64/v8
            dockerfile: dockerfiles/base/Dockerfile-jammy
            tags: |
              gvoze32/cloud9-base:arm64v8-jammy
          - distro: noble
            arch: arm64v8
            platform: linux/arm64/v8
            dockerfile: dockerfiles/base/Dockerfile-noble
            tags: |
              gvoze32/cloud9-base:arm64v8-noble
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ matrix.tags }}
