name: Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: focal
            arch: amd64
            platform: linux/amd64
            dockerfile: dockerfiles/amd64/Dockerfile-focal
            tags: |
              gvoze32/cloud9:focal
              gvoze32/cloud9:amd64-focal
          - distro: jammy
            arch: amd64
            platform: linux/amd64
            dockerfile: dockerfiles/amd64/Dockerfile-jammy
            tags: |
              gvoze32/cloud9:jammy
              gvoze32/cloud9:amd64-jammy
          - distro: noble
            arch: amd64
            platform: linux/amd64
            dockerfile: dockerfiles/amd64/Dockerfile-noble
            tags: |
              gvoze32/cloud9:noble
              gvoze32/cloud9:amd64-noble
              gvoze32/cloud9:latest
          - distro: focal
            arch: arm64v8
            platform: linux/arm64/v8
            dockerfile: dockerfiles/arm64v8/Dockerfile-focal
            tags: |
              gvoze32/cloud9:arm64v8-focal
          - distro: jammy
            arch: arm64v8
            platform: linux/arm64/v8
            dockerfile: dockerfiles/arm64v8/Dockerfile-jammy
            tags: |
              gvoze32/cloud9:arm64v8-jammy
          - distro: noble
            arch: arm64v8
            platform: linux/arm64/v8
            dockerfile: dockerfiles/arm64v8/Dockerfile-noble
            tags: |
              gvoze32/cloud9:arm64v8-noble
          - distro: focal
            arch: arm32v7
            platform: linux/arm/v7
            dockerfile: dockerfiles/arm32v7/Dockerfile-focal
            tags: |
              gvoze32/cloud9:arm32v7-focal
          - distro: jammy
            arch: arm32v7
            platform: linux/arm/v7
            dockerfile: dockerfiles/arm32v7/Dockerfile-jammy
            tags: |
              gvoze32/cloud9:arm32v7-jammy
          - distro: noble
            arch: arm32v7
            platform: linux/arm/v7
            dockerfile: dockerfiles/arm32v7/Dockerfile-noble
            tags: |
              gvoze32/cloud9:arm32v7-noble
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ matrix.tags }}
