#!/usr/bin/with-contenv bash

# Ensure jayanode user exists
if ! id -u jayanode >/dev/null 2>&1; then
  useradd -m -s /bin/bash jayanode
fi

# check for lock file to only run git operations once
if [ ! -e /lock.file ]; then
  # give jayanode a sudo shell for development
  chsh jayanode -s /bin/bash
  sed -e 's/%sudo	ALL=(ALL:ALL) ALL/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/g' \
    -i /etc/sudoers
  sed -e 's/^wheel:\(.*\)/wheel:\1,jayanode/g' -i /etc/group
  # create directory for project
  mkdir -p /workspace
  # make sure URL is set and folder is empty to clone workspace 
  if [ -n "${GITURL:-}" ] && [ ! "$(/bin/ls -A /workspace 2>/dev/null)" ] ; then \
    # clone the url the user passed to this directory
    git clone "${GITURL}" /workspace
  fi
else
  # lock exists not importing project this is a restart
  echo "Lock exists just starting cloud9"
fi

# create lock file after first run
touch /lock.file

# permissions
mkdir -p /c9sdk/build/standalone
echo "[cont-init.d] Setting permissions this may take some time"
chown -R jayanode:jayanode \
 /c9sdk/build/standalone \
 /workspace \
 /c9bins